try {
    console.log(naoExisto);
} catch(error) {
    console.log('naoExisto n√£o existe!')
}
